import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Bot, FileText, TrendingUp, DollarSign, Calendar } from "lucide-react";
import { deepResearchData } from "@/lib/mock-data";

export function DeepResearchFeed() {
  const { raw_report, extracted_sales } = deepResearchData;

  // Simple parsing for the markdown-like report to make it readable
  const formatReport = (text: string) => {
    return text.split('\n').map((line, i) => {
      if (line.startsWith('# ')) return <h2 key={i} className="text-xl font-bold mt-4 mb-2 text-primary">{line.replace('# ', '')}</h2>;
      if (line.startsWith('## ')) return <h3 key={i} className="text-lg font-bold mt-3 mb-2 text-foreground">{line.replace('## ', '')}</h3>;
      if (line.startsWith('### ')) return <h4 key={i} className="text-md font-semibold mt-2 mb-1 text-muted-foreground">{line.replace('### ', '')}</h4>;
      if (line.startsWith('* ')) return <li key={i} className="ml-4 mb-1 text-sm list-disc pl-1">{line.replace('* ', '')}</li>;
      if (line === '---') return <hr key={i} className="my-4 border-border/50" />;
      return <p key={i} className="mb-2 text-sm leading-relaxed text-muted-foreground">{line}</p>;
    });
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 h-full">
      {/* Report Section */}
      <Card className="lg:col-span-2 bg-card border-primary/20 shadow-[0_0_20px_rgba(234,179,8,0.05)] h-full flex flex-col">
        <CardHeader className="border-b border-border/50 bg-primary/5">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Bot className="w-5 h-5 text-primary" />
              <CardTitle className="font-display tracking-wide text-lg">Deep Research Agent</CardTitle>
            </div>
            <Badge variant="outline" className="border-primary/50 text-primary bg-primary/10">
              Completed
            </Badge>
          </div>
          <CardDescription>Comprehensive market analysis generated by AI Agent</CardDescription>
        </CardHeader>
        <CardContent className="p-0 flex-1 min-h-[400px]">
          <ScrollArea className="h-[600px] p-6">
            <div className="prose prose-invert prose-sm max-w-none">
              {formatReport(raw_report)}
            </div>
          </ScrollArea>
        </CardContent>
      </Card>

      {/* Extracted Data Section */}
      <div className="space-y-6">
        <Card className="bg-card border-border/50">
          <CardHeader>
            <CardTitle className="text-sm font-medium uppercase tracking-wider text-muted-foreground flex items-center gap-2">
              <TrendingUp className="w-4 h-4 text-primary" />
              Agent Findings
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex justify-between items-center p-3 bg-secondary/30 rounded-lg border border-border/50">
              <span className="text-sm text-muted-foreground">Data Points</span>
              <span className="font-mono font-bold text-foreground">{extracted_sales.length} Verified</span>
            </div>
            <div className="flex justify-between items-center p-3 bg-secondary/30 rounded-lg border border-border/50">
              <span className="text-sm text-muted-foreground">Price Range</span>
              <span className="font-mono font-bold text-foreground">$35k - $139k</span>
            </div>
            <div className="flex justify-between items-center p-3 bg-secondary/30 rounded-lg border border-border/50">
              <span className="text-sm text-muted-foreground">Market Status</span>
              <span className="font-bold text-amber-500">Bifurcated</span>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card border-border/50 flex-1">
          <CardHeader>
            <CardTitle className="text-sm font-medium uppercase tracking-wider text-muted-foreground flex items-center gap-2">
              <DollarSign className="w-4 h-4 text-primary" />
              Recent Sales & Asks
            </CardTitle>
          </CardHeader>
          <CardContent className="p-0">
            <ScrollArea className="h-[350px]">
              <div className="divide-y divide-border/50">
                {extracted_sales.map((sale, i) => (
                  <div key={i} className="p-4 hover:bg-secondary/30 transition-colors">
                    <div className="flex justify-between items-start mb-1">
                      <span className="font-bold font-mono text-foreground">
                        ${sale.price.toLocaleString()}
                      </span>
                      <Badge variant={sale.price_type === 'Sold' ? 'default' : 'secondary'} className="text-[10px]">
                        {sale.price_type}
                      </Badge>
                    </div>
                    <p className="text-xs text-muted-foreground line-clamp-2 mb-2">
                      {sale.description}
                    </p>
                    <div className="flex justify-between items-center text-[10px] text-muted-foreground/70 uppercase tracking-wider">
                      <span>{sale.source}</span>
                      <span className="flex items-center gap-1">
                        <Calendar className="w-3 h-3" /> 2025
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </ScrollArea>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
